export const HOME = '/'
export const LOGIN = '/login'
export const SESSIONS_TODAY = '/sessions-today'
export const SESSIONS_HISTORY = '/sessions-history'
export const SESSION_DETAIL = '/sessions/:sessionId'
